config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/PalomoIFCA/testsqaaasgitci:
      branch: main
      repo: https://gitlab.com/PalomoIFCA/testsqaaasgitci
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci git:
        commands:
        - /usr/bin/env sh .sqa/script.cyan_joyful_finch.sh
        container: qc.acc_coffee_helpful_hippopotamus
  QC.Doc:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paprika_funny_fox.sh
        container: qc.doc_sunset_reserved_condor
      gitlab.com/PalomoIFCA/testsqaaasgitci git:
        commands:
        - /usr/bin/env sh .sqa/script.cloud_diplomatic_snail.sh
        container: qc.doc_glaucous_realistic_caribou
      gitlab.com/PalomoIFCA/testsqaaasgitci markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lapis_proactive_newt.sh
        container: qc.doc_cerise_confused_jackal
  QC.Lic:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wisteria_responsible_porcupine.sh
        container: qc.lic_lilac_perceptive_fox
  QC.Sec:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci bandit:
        commands:
        - /usr/bin/env sh .sqa/script.blush_diplomatic_camel.sh
        container: qc.sec_cerulean_intuitive_dugong
  QC.Sty:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci flake8:
        commands:
        - /usr/bin/env sh .sqa/script.azure_articulate_thrush.sh
        container: qc.sty_strawberry_responsible_finch
  QC.Uni:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci pytest:
        commands:
        - /usr/bin/env sh .sqa/script.pistachio_insightful_snail.sh
        container: qc.uni_porcelain_pensive_turkey
  QC.Ver:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.mist_silly_hornbill.sh
        container: qc.ver_mist_witty_uakari
timeout: 5400
