config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.com/PalomoIFCA/testsqaaasgitci:
      branch: main
      repo: https://gitlab.com/PalomoIFCA/testsqaaasgitci
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci git:
        commands:
        - /usr/bin/env sh .sqa/script.cosmos_dramatic_snail.sh
        container: qc.acc_mulberry_driven_sparrow
  QC.Doc:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cinnabar_forgiving_bat.sh
        container: qc.doc_yellow_shy_grizzly
      gitlab.com/PalomoIFCA/testsqaaasgitci git:
        commands:
        - /usr/bin/env sh .sqa/script.turmeric_reliable_warthog.sh
        container: qc.doc_ice_cautious_gecko
      gitlab.com/PalomoIFCA/testsqaaasgitci markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.glacier_flexible_puffin.sh
        container: qc.doc_rosewater_relaxed_gorilla
  QC.Lic:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci licensee:
        commands:
        - /usr/bin/env sh .sqa/script.tundra_vigilant_serval.sh
        container: qc.lic_echelon_carefree_nymph
  QC.Sec:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci bandit:
        commands:
        - /usr/bin/env sh .sqa/script.ice_aware_spren.sh
        container: qc.sec_raven_friendly_wombat
  QC.Sty:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci flake8:
        commands:
        - /usr/bin/env sh .sqa/script.ecru_energetic_chameleon.sh
        container: qc.sty_carmine_blissful_thrush
  QC.Uni:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci pytest:
        commands:
        - /usr/bin/env sh .sqa/script.sage_loving_lobster.sh
        container: qc.uni_onyx_wondrous_seahorse
  QC.Ver:
    repos:
      gitlab.com/PalomoIFCA/testsqaaasgitci get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.malachite_hopeful_cassowary.sh
        container: qc.ver_lapis_feisty_dormouse
timeout: 5400
