config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: fix/updatego
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    gitlab.acnca.pt/palomoIFCA/testsqaaasgitci:
      branch: main
      repo: https://gitlab.acnca.pt/palomoIFCA/testsqaaasgitci
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci git:
        commands:
        - /usr/bin/env sh .sqa/script.ultramarine_upbeat_octopus.sh
        container: qc.acc_tan_enthusiastic_clownfish
  QC.Doc:
    repos:
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cream_careful_thrush.sh
        container: qc.doc_ceru_graceful_serval
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci git:
        commands:
        - /usr/bin/env sh .sqa/script.walnut_pensive_swan.sh
        container: qc.doc_rose_restless_jaguar
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gold_reserved_chinchilla.sh
        container: qc.doc_wisteria_pensive_jaguar
  QC.Lic:
    repos:
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci licensee:
        commands:
        - /usr/bin/env sh .sqa/script.puce_logical_seahorse.sh
        container: qc.lic_indigo_elated_antelope
  QC.Sec:
    repos:
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci bandit:
        commands:
        - /usr/bin/env sh .sqa/script.verdant_attentive_cassowary.sh
        container: qc.sec_butter_sweet_kingfisher
  QC.Sty:
    repos:
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluebell_cranky_tapir.sh
        container: qc.sty_mahogany_practical_llama
  QC.Uni:
    repos:
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci pytest:
        commands:
        - /usr/bin/env sh .sqa/script.raven_vibrant_ferret.sh
        container: qc.uni_currant_hopeful_emu
  QC.Ver:
    repos:
      gitlab.acnca.pt/palomoIFCA/testsqaaasgitci get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flint_flexible_otter.sh
        container: qc.ver_maroon_brilliant_echidna
timeout: 5400
